### ISSUE TITLE
Add dependencies

### ISSUE THREAD

**Issue by mxochicale** [air4children/slides#6]
Add instructions for the required dependencies to reproduce the slides.

**Comment by mxochicale** [comment]
Something like this https://github.com/mxochicale/riots-sth-20200225/tree/master/dependencies

**Comment by roboticslibre** [comment]
add https://github.com/mxochicale/github

**Comment by mxochicale** [comment]
commit https://github.com/air4children/slides/commit/4355a15b4a89db6a477376a95f2be7154d27e514 close this one
